# Generated by Django 4.2.15 on 2024-08-26 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-CreatedDate', 'ProductID'), 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
