# Generated by Django 4.2.15 on 2024-08-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_remove_subvariant_stock_remove_variant_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductID',
            field=models.BigIntegerField(),
        ),
    ]
