# Generated by Django 4.2.15 on 2024-08-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_alter_products_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductID',
            field=models.BigIntegerField(unique=True),
        ),
    ]
