# Generated by Django 4.2.15 on 2024-08-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_variant_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='subvariants',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
