# Generated by Django 4.2.15 on 2024-08-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_alter_variant_subvariants'),
    ]

    operations = [
        migrations.AddField(
            model_name='subvariant',
            name='stock',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='subvariant',
            table=None,
        ),
    ]
