# Generated by Django 4.2.15 on 2024-08-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_subvariant_stock_alter_subvariant_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='subvariants',
        ),
        migrations.AlterField(
            model_name='subvariant',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subvariants', to='Backend.variant'),
        ),
        migrations.AlterModelTable(
            name='subvariant',
            table='product_subvariant',
        ),
    ]
